baseurl = "/"
theme = "hermit-mod"
languageCode = "en-us"
defaultContentLanguage = "en"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

[languages]
  [languages.en]
    title = "ana"
    subtitle = ""
    keywords = ""
    copyright = ""
    # menuMore = "show more"
    # writtenBy = "written by"
    # readMore = "read more"
    # readOtherPosts = "read other posts"
    # newerPosts = "newer posts"
    # olderPosts = "older posts"
    # minuteReadingTime = "min read"
    # dateFormatSingle = "2006-01-02"
    # dateFormatList = "2006-01-02"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts"

# Social Icons
[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/anamartinazzo"

[[params.social]]
  name = "github"
  url = "https://github.com/amartinazzo"
